//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookTechnoCMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuModule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Controller { get; set; }
        public string ViewUrl { get; set; }
        public string Path { get; set; }
    }
}
